spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
event:
  channel:
    type: ${CHANNE_TYPE:RABBIT}
    host: ${CHANNEL_HOST:localhost}
    port: ${CHANNEL_PORT:5672}

